const PERMISSIONS = {
  TICKETS_CREATE: 'tickets:create',
  TICKETS_READ_OWN: 'tickets:read_own',
  TICKETS_READ_ASSIGNED: 'tickets:read_assigned',
  TICKETS_READ_ALL: 'tickets:read_all',
  TICKETS_UPDATE_OWN: 'tickets:update_own',
  TICKETS_UPDATE_STATUS: 'tickets:update_status',
  TICKETS_UPDATE_PRIORITY: 'tickets:update_priority',
  TICKETS_ASSIGN: 'tickets:assign',
  TICKETS_ESCALATE: 'tickets:escalate',
  TICKETS_DELETE: 'tickets:delete',

  COMMENTS_CREATE_PUBLIC: 'comments:create_public',
  COMMENTS_CREATE_INTERNAL: 'comments:create_internal',
  COMMENTS_READ_INTERNAL: 'comments:read_internal',

  SLA_READ: 'sla:read',
  SLA_MANAGE_POLICIES: 'sla:manage_policies',
  SLA_OVERRIDE: 'sla:override',

  PREDICTIONS_READ: 'predictions:read',
  PREDICTIONS_RUN: 'predictions:run',

  USERS_READ: 'users:read',
  USERS_MANAGE: 'users:manage',
  USERS_CHANGE_ROLE: 'users:change_role',
  ORGS_MANAGE: 'orgs:manage',

  AUDIT_READ: 'audit:read',
  SECURITY_READ: 'security:read',
  ANALYTICS_READ: 'analytics:read'
};

const ROLE_PERMISSIONS = {
  CUSTOMER: [
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_READ_OWN,
    PERMISSIONS.TICKETS_UPDATE_OWN,
    PERMISSIONS.COMMENTS_CREATE_PUBLIC,
    PERMISSIONS.SLA_READ
  ],
  AGENT: [
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_READ_OWN,
    PERMISSIONS.TICKETS_READ_ASSIGNED,
    PERMISSIONS.TICKETS_UPDATE_STATUS,
    PERMISSIONS.COMMENTS_CREATE_PUBLIC,
    PERMISSIONS.COMMENTS_CREATE_INTERNAL,
    PERMISSIONS.COMMENTS_READ_INTERNAL,
    PERMISSIONS.SLA_READ,
    PERMISSIONS.PREDICTIONS_READ
  ],
  MANAGER: [
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_READ_ALL,
    PERMISSIONS.TICKETS_UPDATE_STATUS,
    PERMISSIONS.TICKETS_UPDATE_PRIORITY,
    PERMISSIONS.TICKETS_ASSIGN,
    PERMISSIONS.TICKETS_ESCALATE,
    PERMISSIONS.COMMENTS_CREATE_PUBLIC,
    PERMISSIONS.COMMENTS_CREATE_INTERNAL,
    PERMISSIONS.COMMENTS_READ_INTERNAL,
    PERMISSIONS.SLA_READ,
    PERMISSIONS.SLA_MANAGE_POLICIES,
    PERMISSIONS.SLA_OVERRIDE,
    PERMISSIONS.PREDICTIONS_READ,
    PERMISSIONS.PREDICTIONS_RUN,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.ANALYTICS_READ
  ],
  ADMIN: Object.values(PERMISSIONS)
};

function hasPermission(role, permission) {
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission
};
